# Generated by Django 6.1 on 2026-08-20 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('CCTV & Security', 'CCTV & Security'), ('Internet & Wi-Fi', 'Internet & Wi-Fi'), ('Air Conditioning', 'Air Conditioning'), ('Appliances', 'Appliances'), ('Carpentry', 'Carpentry'), ('Painting', 'Painting'), ('Cleaning', 'Cleaning'), ('General Repairs', 'General Repairs')], max_length=40)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=120)),
                ('urgency', models.CharField(choices=[('ASAP', 'As soon as possible'), ('Today', 'Today'), ('This week', 'This week'), ('Just exploring', 'Just exploring options')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('matched_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_jobs', to='providers.provider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
