# Generated by Django 6.1 on 2026-08-20 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('CCTV & Security', 'CCTV & Security'), ('Internet & Wi-Fi', 'Internet & Wi-Fi'), ('Air Conditioning', 'Air Conditioning'), ('Appliances', 'Appliances'), ('Carpentry', 'Carpentry'), ('Painting', 'Painting'), ('Cleaning', 'Cleaning'), ('General Repairs', 'General Repairs')], max_length=40)),
                ('area', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
